// Code generated by "stringer -type=ConnState -linecomment -output=conn_state_stringer.go"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnStateInit-0]
	_ = x[ConnStateStatus-1]
	_ = x[ConnStateLogin-2]
	_ = x[ConnStatePlay-3]
	_ = x[ConnStateClose-4]
}

const _ConnState_name = "initstatusloginplayclose"

var _ConnState_index = [...]uint8{0, 4, 10, 15, 19, 24}

func (i ConnState) String() string {
	if i < 0 || i >= ConnState(len(_ConnState_index)-1) {
		return "ConnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnState_name[_ConnState_index[i]:_ConnState_index[i+1]]
}
